### ISSUE TITLE
Tracking issue for documentation

### ISSUE THREAD

**Issue by passcod** [passcod/notify#135]
## Rustdoc

- [x] Backend
- [x] Inotify
- [x] Kqueue
- [x] Poll-tree
- [ ] Notify (frontend)
- [x] #140
- [ ] FSEvent (#139)
- [ ] Windows (#141)

## Guides

- [x] Readme
- [ ] Basic usage (very quick look in readme)
- [ ] Usage looking at how events work
- [ ] Usage looking at how errors work (both init and stream)
- [ ] Usage for the future-less API
- [x] Big picture look at how notify works
- [ ] A description of leaks in the abstraction: inotify limits, open files limits, fsevents security limitations, networked filesystems and fuse, etc
- [ ] A list of all cases in which panics may be expected, if any (should also be reflected in API docs)
- [x] How to contribute
- [ ] Debouncing guide
- [ ] Tracking renames etc
- [ ] Backend implementation
- [ ] Deep dive into internals
- [ ] Précis on some low-level or internal interfaces that don't fit in the dive

**Comment by passcod** [comment]
Closing some v5 issues that are outdated and/or not actionable now.
